trainer: imgrec_trainer_lainr_constant
warmup_epochs: 0
train_dataset:
  name: imgrec_dataset
  args:
    imageset:
      name: celeba
      args: {root_path: /home/idies/.cache/kagglehub/datasets/jessicali9530/celeba-dataset/versions/2, split: train}
    resize: 178
  loader:
    batch_size: 8
    num_workers: 8

test_dataset:
  name: imgrec_dataset
  args:
    imageset:
      name: celeba
      args: {root_path: /home/idies/.cache/kagglehub/datasets/jessicali9530/celeba-dataset/versions/2, split: test}
    resize: 178
  loader:
    batch_size: 8
    num_workers: 8

model:
  name: mamba_lainr_inr
  args:
    tokenizer:
      name: mamba_patch_tokenizer
      args: {input_size: 178, patch_size: 9, padding: 1, dim: 256, pos_emb: 'fourier'}
    hyponet:
      name: lainr_mlp
      args: {feature_dim: 256, input_dim: 2, output_dim: 3, sigma_q: 16, sigma_ls: [128, 32]}
    mamba_encoder:
      name: mamba_encoder
      args: {dim: 256, depth: 6, ff_dim: 1024}
    type: 'equidistant'
    n_group: 1
    num_lp: 256

optimizer:
  name: adamw
  args: {lr: 1.e-4}
max_epoch: 300

eval_epoch: 1
vis_epoch: 5
