trainer: imgrec_trainer

train_dataset:
  name: imgrec_dataset
  args:
    imageset:
      name: cifar_10
      args: {root_path: /home/idies/.cache/, split: train}
    resize: 32
  loader:
    batch_size: 16
    num_workers: 8

test_dataset:
  name: imgrec_dataset
  args:
    imageset:
      name: cifar_10
      args: {root_path: /home/idies/.cache/, split: test}
    resize: 32
  loader:
    batch_size: 16
    num_workers: 8

model:
  name: trans_inr
  args:
    tokenizer:
      name: imgrec_tokenizer
      args: {input_size: 32, patch_size: 2}
    hyponet:
      name: hypo_mlp
      args: {in_dim: 2, out_dim: 3, out_bias: 0.5, depth: 5, hidden_dim: 256, use_pe: true, pe_dim: 128}
    n_groups: 64
    transformer_encoder:
      name: transformer_encoder
      args: {dim: 512, depth: 6, n_head: 12, head_dim: 64, ff_dim: 2048}

optimizer:
  name: adam
  args: {lr: 1.e-4}
max_epoch: 30

eval_epoch: 1
vis_epoch: 5
