trainer: imgrec_trainer_lainr_sr

train_dataset:
  name: sr_dataset
  args:
    imageset:
      name: celebahq_sr
      args: {root_path: /home/idies/.cache/kagglehub/datasets/lamsimon/celebahq/versions/1/, split: train}
    resize: 1024
    downsample_ratio: 4
  loader:
    batch_size: 16
    num_workers: 8
  

test_dataset:
  name: sr_dataset
  args:
    imageset:
      name: celebahq_sr
      args: {root_path: /home/idies/.cache/kagglehub/datasets/lamsimon/celebahq/versions/1/, split: test}
    resize: 1024
    downsample_ratio: 4
  loader:
    batch_size: 16
    num_workers: 8

model:
  name: mamba_lainr_inr
  args:
    tokenizer:
      name: mamba_patch_tokenizer
      args: {input_size: 256, patch_size: 16, dim: 256, pos_emb: 'fourier'}
    hyponet:
      name: lainr_mlp
      args: {feature_dim: 64, input_dim: 2, output_dim: 3, sigma_q: 16, sigma_ls: [128, 32]}
    mamba_encoder:
      name: mamba_encoder
      args: {dim: 256, depth: 6, ff_dim: 1024}
    type: 'equidistant'
    n_group: 1
    num_lp: 256

optimizer:
  name: adamw
  args: {lr: 1.e-4}
max_epoch: 80

eval_epoch: 1
vis_epoch: 5
