from .trainers import register, trainers_dict
from . import base_trainer
from . import base_trainer_slurm
from . import base_trainer_grad
from . import imgrec_trainer
from . import imgrec_trainer_grad
from . import imgrec_trainer2
from . import nvs_trainer
from . import imgrec_trainer_lainr
from . import imgrec_trainer_lainr_constant
from . import imgrec_trainer_constant
from . import imgrec_trainer_lainr_sr
from . import imgrec_trainer_lainr_ddp
from . import base_fmri_trainer_slurm
from . import fmri_trainer_lainr_ddp
from . import fmri_trainer_lainr_2d
from . import fmri_trainer_lainr_ddp_2d
from . import fmri_trainer_lainr_ddp_resize
from . import fmri_trainer_lainr_ddp_resize_lr
from . import fmri_trainer_lainr_ddp_resize_lr_batched